// auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_TOKEN = 'FETCH_TOKEN';
export const AUTH_ERROR = 'AUTH_ERROR';

// user
export const FETCH_USER = 'FETCH_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

// service
export const SERVICE = 'SERVICE';
export const SERVICE_SUCCESS = 'SERVICE_SUCCESS';
export const SERVICE_FAILURE = 'SERVICE_FAILURE';
export const POSTING = 'POSTING';
export const POST_SUCCESS = 'POST_SUCCESS';
export const POST_FAILURE = 'POST_FAILURE';

// goods
export const FETCH_GOODS = 'FETCH_GOODS';
export const RECEIVE_GOODS = 'RECEIVE_GOODS';
export const SEARCH_GOODS = 'SEARCH_GOODS';
export const RECEIVE_SEARCH = 'RECEIVE_SEARCH';
export const GET_GOOD = 'GET_GOOD';
export const RECEIVE_ONE_GOOD = 'RECEIVE_ONE_GOOD';

// cart
export const GET_CART_GOOD_DETAIL = 'GET_CART_GOOD_DETAIL';
export const RECEIVE_ONE_CART = 'RECEIVE_ONE_CART';
export const POST_CART = 'POST_CART';
export const POST_CART_SUCCESS = 'POST_CART_SUCCESS';
export const POST_CART_FAILURE = 'POST_CART_FAILURE';
export const FETCH_CART_DETAIL_FAILURE = 'FETCH_CART_DETAIL_FAILURE';
export const FETCH_CART = 'FETCH_CART';
export const RECEIVE_CART = 'RECEIVE_CART'
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';

// address
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const RECEIVE_ADDRESSES =' RECEIVE_ADDRESSES';
export const FETCH_ADDRESSES_FAILURE = 'FETCH_ADDRESSES_FAILURE';
export const FETCH_ONE_ADDRESS = 'FETCH_ONE_ADDRESS';
export const FETCH_ONE_ADDRESS_FAILURE = 'FETCH_ONE_ADDRESS_FAILURE';
export const RECEIVE_ONE_ADDRESS = 'RECEIVE_ONE_ADDRESS';
export const POST_ADDRESS = 'POST_ADDRESS';
export const POST_ADDRESS_SUCCESS = 'POST_ADDRESS_SUCCESS';
export const POST_ADDRESS_FAILURE = 'POST_ADDRESS_FAILURE';

// order
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const POST_ORDER = 'POST_ORDER';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';

// advs
export const FETCH_ADVS = 'FETCH_ADVS';
export const FETCH_ADVS_SUCCESS = 'FETCH_ADVS_SUCCESS';
export const FETCH_ADVS_FAILURE = 'FETCH_ADVS_FAILURE';
